import { withApi } from '@/lib/http';
import { NextRequest, NextResponse } from 'next/server';
import { requireSession, errorResponse } from '@/lib/http';
import { supabase, dbReady } from '@/lib/db';
import { ROUTABLE_SKILLS } from '@/lib/skills/registry';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';
// The harvested catalog is ~3.5MB of instructions across 341 skills; the upsert
// runs in batches but still needs headroom on a cold start.
export const maxDuration = 60;

// POST /api/skills/sync — push the bundled skill catalog into the `skills` table.
//
// WHY THIS EXISTS
// `lib/skills/registry.ts` (12 curated) + `lib/skills/harvested.ts` (341 OSS,
// emitted by scripts/harvest-skills.ts) are compiled INTO the app, but nothing
// ever wrote them to the database. `skills` was empty in production, so
// `account_skills` had nothing to reference, `loadEnabledSkillsForAgent`
// returned [], and Hermes had no catalog rows to route against — the assistant
// ran with zero skills and said nothing about it.
//
// Seeding from a migration was the alternative and it is the wrong shape: the
// content is regenerated by the harvest script, so it would mean a new 3.5MB
// migration on every harvest. This endpoint is idempotent and re-runnable —
// run it after each harvest and the catalog converges.
//
// Rows are GLOBAL (account_id IS NULL), matching migration 025's
// idx_skills_global_slug unique index. Account-authored custom skills
// (account_id NOT NULL) live in the same table and are never touched here.
//
// Owner-only: this rewrites a shared catalog every tenant reads from.
async function POST__impl(request: NextRequest) {
  const { session, error } = await requireSession(request);
  if (error) return error;
  if (session.role !== 'owner') {
    return NextResponse.json({ error: 'Owners only' }, { status: 403 });
  }
  if (!dbReady()) {
    return NextResponse.json({ error: 'Database not configured' }, { status: 503 });
  }

  try {
    const rows = ROUTABLE_SKILLS.map((s) => ({
      account_id: null,
      slug: s.id,
      name: s.name,
      category: s.category,
      // `when` is the one-line relevance trigger Hermes reads to shortlist.
      // It maps to `description` because that is the column the routing query
      // and the catalog UI both read.
      description: s.when,
      // `systemModule` is the prompt fragment injected once a skill is chosen.
      instructions: s.systemModule,
      source: 'builtin',
      inspired_by: s.inspiredBy,
    })).filter((r) => r.slug && r.name && r.instructions);

    // Batch: a single 3.5MB statement risks the request body limit and gives no
    // partial progress. 50 keeps each round-trip well under a megabyte.
    const BATCH = 50;
    let upserted = 0;
    const failures: { batch: number; error: string }[] = [];

    for (let i = 0; i < rows.length; i += BATCH) {
      const chunk = rows.slice(i, i + BATCH);
      const { error: upsertErr } = await supabase
        .from('skills')
        .upsert(chunk, { onConflict: 'slug', ignoreDuplicates: false });
      if (upsertErr) {
        failures.push({ batch: i / BATCH, error: upsertErr.message });
      } else {
        upserted += chunk.length;
      }
    }

    const { count } = await supabase
      .from('skills')
      .select('*', { count: 'exact', head: true })
      .is('account_id', null);

    return NextResponse.json({
      ok: failures.length === 0,
      candidates: rows.length,
      upserted,
      globalCatalogSize: count ?? null,
      failures,
    });
  } catch (e) {
    return errorResponse(e);
  }
}

export const POST = withApi(POST__impl as any, { route: '/api/skills/sync', method: 'POST' });
