import { withApi } from '@/lib/http';
import { NextRequest, NextResponse } from 'next/server';
import { requireSession, errorResponse } from '@/lib/http';
import { supabase, dbReady } from '@/lib/db';
import { ROUTABLE_SKILLS } from '@/lib/skills/registry';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';
// The harvested catalog is ~3.5MB of instructions across 341 skills; the upsert
// runs in batches but still needs headroom on a cold start.
export const maxDuration = 60;

// POST /api/skills/sync — push the bundled skill catalog into the `skills` table.
//
// WHY THIS EXISTS
// `lib/skills/registry.ts` (12 curated) + `lib/skills/harvested.ts` (341 OSS,
// emitted by scripts/harvest-skills.ts) are compiled INTO the app, but nothing
// ever wrote them to the database. `skills` was empty in production, so
// `account_skills` had nothing to reference, `loadEnabledSkillsForAgent`
// returned [], and Hermes had no catalog rows to route against — the assistant
// ran with zero skills and said nothing about it.
//
// Seeding from a migration was the alternative and it is the wrong shape: the
// content is regenerated by the harvest script, so it would mean a new 3.5MB
// migration on every harvest. This endpoint is idempotent and re-runnable —
// run it after each harvest and the catalog converges.
//
// Rows are GLOBAL (account_id IS NULL), matching migration 025's
// idx_skills_global_slug unique index. Account-authored custom skills
// (account_id NOT NULL) live in the same table and are never touched here.
//
// Owner-only: this rewrites a shared catalog every tenant reads from.
async function POST__impl(request: NextRequest) {
  const { session, error } = await requireSession(request);
  if (error) return error;
  if (session.role !== 'owner') {
    return NextResponse.json({ error: 'Owners only' }, { status: 403 });
  }
  if (!dbReady()) {
    return NextResponse.json({ error: 'Database not configured' }, { status: 503 });
  }

  try {
    const rows = ROUTABLE_SKILLS.map((s) => ({
      account_id: null,
      slug: s.id,
      name: s.name,
      category: s.category,
      // `when` is the one-line relevance trigger Hermes reads to shortlist.
      // It maps to `description` because that is the column the routing query
      // and the catalog UI both read.
      description: s.when,
      // `systemModule` is the prompt fragment injected once a skill is chosen.
      instructions: s.systemModule,
      source: 'builtin',
      inspired_by: s.inspiredBy,
    })).filter((r) => r.slug && r.name && r.instructions);

    // NO upsert/onConflict here. The catalog's uniqueness is enforced by a
    // PARTIAL index — idx_skills_global_slug ON skills(slug) WHERE account_id
    // IS NULL (migration 025) — and ON CONFLICT cannot target a partial index
    // without restating its predicate, which PostgREST's `onConflict` has no way
    // to express. Attempting it fails every batch with "no unique or exclusion
    // constraint matching the ON CONFLICT specification".
    //
    // Delete-then-insert is NOT an option either: account_skills references
    // skills(id) ON DELETE CASCADE, so dropping catalog rows would silently
    // delete every account's enabled-skill selections.
    //
    // So: read the global slugs that already exist, then INSERT the new ones and
    // UPDATE the rest by slug. Both halves stay scoped to account_id IS NULL, so
    // an account's own custom skills are never touched even if they share a slug.
    const { data: existingRows, error: readErr } = await supabase
      .from('skills')
      .select('slug')
      .is('account_id', null);
    if (readErr) {
      return NextResponse.json({ error: `Could not read catalog: ${readErr.message}` }, { status: 500 });
    }
    const existing = new Set((existingRows || []).map((r: any) => r.slug as string));

    const toInsert = rows.filter((r) => !existing.has(r.slug));
    const toUpdate = rows.filter((r) => existing.has(r.slug));

    const BATCH = 50;
    let inserted = 0;
    let updated = 0;
    const failures: { stage: string; batch: number; error: string }[] = [];

    for (let i = 0; i < toInsert.length; i += BATCH) {
      const chunk = toInsert.slice(i, i + BATCH);
      const { error } = await supabase.from('skills').insert(chunk);
      if (error) failures.push({ stage: 'insert', batch: i / BATCH, error: error.message });
      else inserted += chunk.length;
    }

    // Updates go one row at a time: there is no bulk-update-by-key in PostgREST
    // that does not route through the same ON CONFLICT problem. Only rows whose
    // content actually changed matter, and on a steady-state re-run this loop is
    // the whole cost — acceptable for an owner-triggered, occasional sync.
    for (const r of toUpdate) {
      const { error } = await supabase
        .from('skills')
        .update({
          name: r.name, category: r.category, description: r.description,
          instructions: r.instructions, source: r.source, inspired_by: r.inspired_by,
        })
        .eq('slug', r.slug)
        .is('account_id', null);
      if (error) failures.push({ stage: 'update', batch: -1, error: error.message });
      else updated += 1;
    }
    const upserted = inserted + updated;

    const { count } = await supabase
      .from('skills')
      .select('*', { count: 'exact', head: true })
      .is('account_id', null);

    return NextResponse.json({
      ok: failures.length === 0,
      candidates: rows.length,
      inserted,
      updated,
      upserted,
      globalCatalogSize: count ?? null,
      failures,
    });
  } catch (e) {
    return errorResponse(e);
  }
}

export const POST = withApi(POST__impl as any, { route: '/api/skills/sync', method: 'POST' });
