INSERT INTO brands (id, name, logo_url, active) VALUES
('rentahub', 'Rentahub', 'https://example.com/rentahub.png', TRUE);

INSERT INTO contacts (brand_id, name, email, company, title, segment, engagement_score) VALUES
('rentahub', 'John Doe', 'john@example.com', 'TechVentures Inc', 'CEO', 'investor', 85),
('rentahub', 'Jane Smith', 'jane@example.com', 'VC Funds LLC', 'Partner', 'vc', 92),
('rentahub', 'Bob Johnson', 'bob@example.com', 'Angel Collective', 'Angel Investor', 'angel', 78),
('rentahub', 'Alice Brown', 'alice@example.com', 'Studio Productions', 'Producer', 'studio', 88),
('rentahub', 'Charlie Davis', 'charlie@example.com', 'Film Agency Co', 'Manager', 'agency', 72),
('rentahub', 'Diana Miller', 'diana@example.com', 'ContentHouse', 'Creator', 'creator', 65),
('rentahub', 'Eve Wilson', 'eve@example.com', 'Global Studios', 'Director', 'production', 84),
('rentahub', 'Frank Thomas', 'frank@example.com', 'Capital Partners', 'Founder', 'investor', 91),
('rentahub', 'Grace Lee', 'grace@example.com', 'Digital Ventures', 'VP Strategy', 'vc', 87),
('rentahub', 'Henry Martin', 'henry@example.com', 'Bootstrap Fund', 'Angel', 'angel', 75),
('rentahub', 'Ivy Chen', 'ivy@example.com', 'Media Group', 'Executive Producer', 'studio', 89),
('rentahub', 'Jack Anderson', 'jack@example.com', 'Creative Agency', 'Account Manager', 'agency', 70),
('rentahub', 'Kate Martinez', 'kate@example.com', 'YouTube Stars', 'Influencer', 'creator', 68),
('rentahub', 'Leo Garcia', 'leo@example.com', 'Production House', 'Head of Production', 'production', 86),
('rentahub', 'Mia Rodriguez', 'mia@example.com', 'Tech Investments', 'Principal', 'investor', 90),
('rentahub', 'Noah Taylor', 'noah@example.com', 'Venture Fund', 'Senior Partner', 'vc', 94),
('rentahub', 'Olivia White', 'olivia@example.com', 'New Angels', 'Angel Investor', 'angel', 76),
('rentahub', 'Peter Harris', 'peter@example.com', 'Indie Films', 'Producer', 'studio', 85),
('rentahub', 'Quinn Campbell', 'quinn@example.com', 'Marketing Firm', 'Director', 'agency', 73),
('rentahub', 'Rachel Green', 'rachel@example.com', 'Streaming Network', 'Content Creator', 'creator', 69),
('rentahub', 'Sam Jackson', 'sam@example.com', 'Movie Studio', 'Exec Producer', 'production', 88),
('rentahub', 'Tina Lopez', 'tina@example.com', 'Founders Club', 'Co-Founder', 'investor', 93),
('rentahub', 'Uma Patel', 'uma@example.com', 'Growth Fund', 'Managing Director', 'vc', 91),
('rentahub', 'Victor King', 'victor@example.com', 'Angel Network', 'Member', 'angel', 74),
('rentahub', 'Wendy Zhang', 'wendy@example.com', 'Production Co', 'Line Producer', 'studio', 83),
('rentahub', 'Xavier Scott', 'xavier@example.com', 'Brand Agency', 'Creative Lead', 'agency', 71),
('rentahub', 'Yara Moore', 'yara@example.com', 'Podcast Network', 'Host', 'creator', 67),
('rentahub', 'Zoe Adams', 'zoe@example.com', 'Film Factory', 'Development', 'production', 82),
('rentahub', 'Aaron Bell', 'aaron@example.com', 'Seed Fund', 'Founder', 'investor', 89),
('rentahub', 'Bella Stone', 'bella@example.com', 'Impact Fund', 'Partner', 'vc', 92);
