-- 086_character_ref_storage_path.sql — character_refs.image_url stops being
-- a place a signed URL can be persisted.
--
-- THE DEFECT THIS CLOSES. generateBrandImage (lib/capabilities/content.ts)
-- produced a generated anchor image, and createCharacterRef
-- (lib/content/store.ts) stored whatever URL it was handed in
-- character_refs.image_url. Once generated images moved off
-- `public/generated/` and onto lib/storage.ts's private, signed-URL bucket
-- (this same packet), that URL is time-limited — and generateBrandImage
-- conditions every future generation on `ref.image_url`
-- (lib/capabilities/content.ts's generateBrandImage run()), so a persisted
-- signed URL silently breaks character consistency the moment it expires.
-- The comment this migration's own defect report quotes ("the anchor image
-- ... must stay reachable — it is a stored asset, not a transient result",
-- migration 050) already said this column holds a stored asset; it just
-- never got a place to keep the STABLE identifier for one.
--
-- THE FIX. `storage_path` holds the bucket-relative path
-- (`<account_id>/<uuid>.<ext>` in lib/storage.ts's GENERATED_BUCKET) when the
-- anchor image was generated by this app. A signed URL is minted from it at
-- USE time (never persisted) — see getCharacterRef's caller in
-- lib/capabilities/content.ts. `image_url` is kept, unchanged and NOT NULL:
-- createCharacterRef's caller can still be a user who pasted a genuinely
-- external image URL (a brand's existing logo, a photo already hosted
-- elsewhere) that has no storage_path at all, and every existing reader of
-- `image_url` keeps working unmodified as the fallback. Nullable, because
-- that external-URL case is exactly the one where no path exists to store.
ALTER TABLE character_refs ADD COLUMN IF NOT EXISTS storage_path TEXT;

-- RLS posture matching its siblings (024/041/062/079/080/081): on, no anon/
-- authenticated policies — the app connects with the service-role key
-- (lib/db.ts) which bypasses RLS, and every read/write is scoped by
-- account_id in application code (lib/content/store.ts). character_refs
-- already had RLS enabled and REVOKEd by migration 050; restated here so this
-- migration is self-contained and the posture is asserted, not assumed.
ALTER TABLE public.character_refs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.character_refs FROM anon, authenticated;

COMMENT ON COLUMN character_refs.storage_path IS
  'Bucket-relative path in lib/storage.ts''s GENERATED_BUCKET for an anchor image this app generated. A signed URL is minted from this at USE time and NEVER persisted anywhere — a persisted signed URL expires and silently breaks character consistency. NULL when image_url is a genuinely external URL the user supplied (no app-owned storage object exists to path to); image_url is then the fallback read path.';
