-- 087_campaign_asset_storage_path.sql — campaign_assets.url stops being a
-- place a signed URL can be persisted.
--
-- THE DEFECT THIS CLOSES. generateImage (lib/capabilities/workspace.ts, and
-- the same-shaped app/api/generate/image/route.ts handler) generated a
-- creative image and persisted whatever URL uploadGenerated() handed back
-- into campaign_assets.url via insertCampaignAsset. Once generated images
-- moved off `public/generated/` and onto lib/storage.ts's private,
-- signed-URL bucket (this same packet), that URL is time-limited
-- (GENERATED_URL_TTL, 24 hours) — and getCampaignAssets (lib/crm.ts) read
-- that column back raw, with no re-signing, so every image attached to a
-- campaign worked for a day and then silently 404d. This is the exact defect
-- 086 already closed for character_refs.image_url; this migration gives
-- campaign_assets the same treatment.
--
-- THE FIX. `storage_path` holds the bucket-relative path
-- (`<account_id>/<uuid>.<ext>` in lib/storage.ts's GENERATED_BUCKET) when the
-- asset was generated by this app. A signed URL is minted from it at READ
-- time (never persisted) — see resolveCampaignAssetUrl in lib/crm.ts. `url`
-- is kept, unchanged and NOT NULL: importAsset (lib/capabilities/
-- campaigns.ts) and POST /api/campaigns/[id]/assets still let a caller attach
-- a genuinely external image/video URL with no storage object behind it at
-- all, and every existing reader of `url` keeps working unmodified as the
-- fallback. Nullable, because that external-URL case is exactly the one
-- where no path exists to store.
ALTER TABLE campaign_assets ADD COLUMN IF NOT EXISTS storage_path TEXT;

-- RLS posture matching its siblings (024/041/050/062/079/080/081/086): on, no
-- anon/authenticated policies — the app connects with the service-role key
-- (lib/db.ts) which bypasses RLS, and every read/write is scoped by
-- account_id in application code (lib/crm.ts, lib/db.ts). campaign_assets
-- already had RLS enabled and REVOKEd; restated here so this migration is
-- self-contained and the posture is asserted, not assumed.
ALTER TABLE public.campaign_assets ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.campaign_assets FROM anon, authenticated;

COMMENT ON COLUMN campaign_assets.storage_path IS
  'Bucket-relative path in lib/storage.ts''s GENERATED_BUCKET for a creative asset this app generated. A signed URL is minted from this at READ time and NEVER persisted anywhere — a persisted signed URL expires and silently 404s. NULL when url is a genuinely external URL the caller supplied via importAsset / POST /api/campaigns/[id]/assets (no app-owned storage object exists to path to); url is then the fallback read path.';
