-- DEPRECATED — do not add to this file, and do not run it.
--
-- This was a hand-maintained concatenation of every migration, and it drifted:
-- 056 through 060 existed as numbered files and had reached production, while
-- this file did not contain them. Since migrations/push.ts read ONLY this file,
-- anyone adding a new migration and running the documented command would have
-- applied nothing and been told it worked.
--
-- push.ts now reads migrations/NNN_*.sql directly, in numeric order. Every one
-- is idempotent (CREATE TABLE IF NOT EXISTS / ADD COLUMN IF NOT EXISTS), so
-- re-running the full set against an up-to-date database is a no-op.
--
-- The file is kept, empty, rather than deleted: something outside this repo may
-- still point at the path, and an empty file that says why is a better answer
-- than a 404 or — far worse — a stale copy someone runs.
--
-- To add a migration: create migrations/NNN_name.sql and run
--   bun run migrations/push.ts
